### ISSUE TITLE
ERROR: INVALID when attempting to run ASM programs (even when using ASMHook)

### ISSUE THREAD

**Issue by SeanTUT** [diabolosse48/PHASM#4]
Device info for clarity: **TI 84 Plus CE Python Edition, OS 5.6.0.0020, jailbroken with arTIfiCE**

So, as I am on OS 5.6, **I cannot run Phasm directly with Asm(prgmPHASM)**, so I use Asmhook, Cesium, or just directly from arTIfiCE.

**When I run Phasm with Cesium**, the program always just says "Phasm is offline" and nothing happens.

**When I run Phasm with Asmhook**, it says "Phasm is online", and all of the features of phasm seem to work, except for running asm programs, which always causes the INVALID error (even though Asmhook is running)

**When I run Phasm directly from arTIfiCE**, the results are exactly the same as running through Asmhook (yes, I did test with clearing RAM to make sure Asmhook wasnt still affecting Phasm)

Is Phasm simply not fully compatible with my calculator, or is this a bug?

**Comment by SeanTUT** [comment]
Will edit this reply with solutions i've tried.

- Cleared RAM before attempting to run
- Making sure the appvar is present and unarchived

**Comment by adriweb** [comment]
I guess it's doing things (the way it tries to launch ASM programs) that are indeed incompatible since OS 5.5 where TI removed ASM support.
AsmHook works around that but is for usage on the homescreen

**Comment by MathisLav** [comment]
Well, that may be weird to say that but I don't recommend you to install PHASM on new OSs/revisions.

It has been many years since the last update of PHASM and it is very reliant on things that are very likely to change from one OS version to another (and unfortunately I don't have time to make it up-to-date).

I think Cesium (or also AsmHook but I don't know it well) are totally ok for the kind of things PHASM was able to do.
